### ISSUE TITLE
Having trouble getting this to work

### ISSUE THREAD

**Issue by juliedavila** [marshyski/cosmodrome#1]
On python 2.7.9 on a virtualenv with your requirements.txt

Made one modification to `data/common.yaml` so that it looks like

``` yaml
# This is the common YAML file which can be queried from any environment
- name: Some Approval
    approved: yes
    job: installapache2
    target: server2

- name: anotherapproval
    approved: yes
    job: pingserver
    target: server1
```

I started the server as `python __init__.py`

It starts fine:
`* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)`

When I try to go to 
`localhost:5000/metadata/common.yaml`

it returns

``` json
{
  "error": "Unknown Endpoint, try '/metadata/common'"
}%
```

when i go to 
`localhost:5000/metadata/common`

it returns

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Perhaps I'm missing something here..
