### ISSUE TITLE
Weird JSON thing

### ISSUE THREAD

**Issue by juliedavila** [marshyski/cosmodrome#3]
I am tinkering around to set a flag for cosmo to return JSON via GET. For some odd reason it removes the curlies.

Tried a couple of things including this:

``` python

@app.route('/metadata/common', methods=["GET"])
def common_metadata():
    """Common Data for All Environments Defined"""
    if os.path.isfile(common):
        if not config_yaml['json']:
            return str(yaml.load(file(common, 'r'))).replace(',', ',\n').replace('{', ' ').replace('}', '\n')
        else:
            return jsonify(yaml.load(open('data/common.yaml', 'r').read()))
    else:
        abort(400)
```

Also tried using the non-flask `json.dumps(yaml.load(common))` way and same result. 

The YAML file common is as follows:

``` yaml

---
    cars:
       trucks: airplanes
    some: value
    thislist:
      - one
      - two
      - three
```

And it gets read fine but it gets returned as

`'cars': 'trucks': 'airplanes' , 'some': 'value', 'thislist': ['one', 'two', 'three']`

So therefore it is not valid json.
Maybe I woke up too early but this is confusing me.
